-- Current Supabase schema used by Bulbul.
-- This file is documentation for the existing project, not a migration.

-- Persistent ADK/local runtime state.
-- Bulbul stores goals in adk_sessions.state under:
--   session_id = 'bulbul:user:{user_id}:goals'
--   state.goals = [...]
create table if not exists adk_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  app_name text not null,
  user_id text not null,
  state jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists adk_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  session_id text not null,
  event_data jsonb not null,
  created_at timestamptz default now()
);

create table if not exists platform_user_sessions (
  id bigint generated by default as identity primary key,
  platform text not null,
  platform_user_id text not null,
  session_id text not null,
  app_name text not null default 'educational_assistant',
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists agent_persona (
  id bigint generated by default as identity primary key,
  user_id text not null,
  key text not null,
  value text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists user_memory (
  id bigint generated always as identity primary key,
  user_id text not null,
  fact_id text not null,
  fact text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists user_engagement (
  platform text not null,
  platform_user_id text not null,
  chat_id bigint not null,
  last_interaction_at timestamptz default now(),
  last_outreach_at timestamptz,
  outreach_enabled boolean default true,
  primary key (platform, platform_user_id)
);
